project:
  type: website

website:
  title: "Aabhas's Portfolio"
  navbar:
    left:
      - href: labs.qmd
        text: Labs
      - href: https://diego2317.github.io/E155-project-site/
        text: Project
      - href: https://hmc-e155.github.io/
        text: Resources



format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



