---
title: "Initial Reflections"
description: "Here I document my first, thoughts, goals, and some initial reflections about E155 course I am taking this semester"
author: "Aabhas Senapati"
date: "8/29/25"
categories:
  - reflection
  - e155
draft: false
---

MicroPs is a class that I had been looking forward to since almost a year ago when I took E85, especially because I have been very passionate about building hardware and electornics projects with IoT. While I have worked with embedded systems before, I don't think I before coming to Mudd, I got the actual understanding of how the libraries or even the actual  microprocessors worked, I just knew how to use them to do what I need to do, without acutally understanding their actual mechanism. I feel like one of my goals from this course, is to be able to get that in-depth understanding of the working of microcontroller, especially after having taken E85, and also build fun projects, that involves application of my skills. I am looking forward to also take-up a project that will involve my understanding of microprocessors, and apply it to do a project which is intersectional, and can be possibly used in ecological sensing. I am also not taking a lot of classes this semester, so that I can focus on quality over quantity, and get good grasp over what I learn and also enjoy this process. Looking forward to what this course and semester entails.
